### ISSUE TITLE
Re-implement Scope.context in coglet (Rust)

### ISSUE THREAD

**Issue by markphelps** [replicate/cog#2852]
## Problem

The `current_scope().context` API was removed when the Python server was replaced by coglet (Rust HTTP server) in #2714. The old Python `Scope` class in `python/cog/server/scope.py` had a `context: Dict[str, str]` field that allowed predictors to access per-prediction context passed via the HTTP request body:

```python
# predictor code
def predict():
    context = cog.current_scope().context
    token = context["replicate_api_token"]
```

```json
POST /predictions
{
  "input": { ... },
  "context": {
    "procedure_source_url": "file:///foo/bar/baz",
    "replicate_api_token": "r8_foop"
  }
}
```

This was introduced in #2330 (v0.14.11). The new coglet `Scope` in `crates/coglet-python/src/metric_scope.rs` only has `metrics` and `record_metric()` — the `context` field was not carried over.

## Impact

Any model that uses `current_scope().context` fails with:
```
AttributeError: 'coglet._sdk.Scope' object has no attribute 'context'
```

This breaks `hello-context` in `replicate/cog-examples` and any production models relying on this API.

## What needs to happen

1. **Rust side (`crates/coglet-python/src/metric_scope.rs`)**: Add a `context: Dict[str, str]` property to the `Scope` PyO3 class
2. **Rust side (`crates/coglet/`)**: Parse the `context` field from the `POST /predictions` request body and pass it through to the `Scope` when creating a `ScopeGuard` for each prediction
3. **Type stubs (`crates/coglet-python/coglet/_sdk/__init__.pyi`)**: Add `context` property to the `Scope` stub
4. **Tests**: Verify `current_scope().context` returns the context dict passed in the prediction request

## Prior art

- #2330 — original implementation (`fea08169`)
- #2714 — coglet rewrite that deleted `python/cog/server/scope.py` (`4bc01628`)
- Old implementation: `python/cog/server/scope.py` had `context: Dict[str, str] = field(default_factory=dict)` on a frozen dataclass, populated via `evolve_scope(context=...)` in the worker before calling predict
